#pragma once
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "sokol_audio.h"
#include "sokol_args.h"
#include "sokol_time.h"
#include "sokol_debugtext.h"
#include "sokol_log.h"
#include "clock.h"
#include "prof.h"
#include "fs.h"
#include "gfx.h"
#include "keybuf.h"
#include "webapi.h"
#include <ctype.h> // isupper, islower, toupper, tolower
