# Makefile

all:	subdirs

clean:	subdirs

subdirs:
	$(MAKE) -C lightpen $(MAKECMDGOALS)
	$(MAKE) -C spritescan $(MAKECMDGOALS)
	$(MAKE) -C bascan $(MAKECMDGOALS)
	$(MAKE) -C modesplit $(MAKECMDGOALS)
	$(MAKE) -C fetchsplit $(MAKECMDGOALS)

# eof
