
TESTS=\
viasr00.prg \
viasr04.prg \
viasr08.prg \
viasr0c.prg \
viasr10.prg \
viasr14.prg \
viasr18.prg \
viasr1c.prg \
viasr00exp.prg \
viasr04exp.prg \
viasr08exp.prg \
viasr0cexp.prg \
viasr10exp.prg \
viasr14exp.prg \
viasr18exp.prg \
viasr1cexp.prg \
viasr00ifr.prg \
viasr04ifr.prg \
viasr08ifr.prg \
viasr0cifr.prg \
viasr10ifr.prg \
viasr14ifr.prg \
viasr18ifr.prg \
viasr1cifr.prg \
viasr00iex.prg \
viasr04iex.prg \
viasr08iex.prg \
viasr0ciex.prg \
viasr10iex.prg \
viasr14iex.prg \
viasr18iex.prg \
viasr1ciex.prg

all: $(TESTS)

viasr00.prg: main.s
	acme -Dexpanded=0 -Dmode=0 -Ddumpreg=10 -f cbm -o viasr00.prg main.s
viasr00exp.prg: main.s
	acme -Dexpanded=1 -Dmode=0 -Ddumpreg=10 -f cbm -o viasr00exp.prg main.s
viasr04.prg: main.s
	acme -Dexpanded=0 -Dmode=1 -Ddumpreg=10 -f cbm -o viasr04.prg main.s
viasr04exp.prg: main.s
	acme -Dexpanded=1 -Dmode=1 -Ddumpreg=10 -f cbm -o viasr04exp.prg main.s
viasr08.prg: main.s
	acme -Dexpanded=0 -Dmode=2 -Ddumpreg=10 -f cbm -o viasr08.prg main.s
viasr08exp.prg: main.s
	acme -Dexpanded=1 -Dmode=2 -Ddumpreg=10 -f cbm -o viasr08exp.prg main.s
viasr0c.prg: main.s
	acme -Dexpanded=0 -Dmode=3 -Ddumpreg=10 -f cbm -o viasr0c.prg main.s
viasr0cexp.prg: main.s
	acme -Dexpanded=1 -Dmode=3 -Ddumpreg=10 -f cbm -o viasr0cexp.prg main.s
viasr10.prg: main.s
	acme -Dexpanded=0 -Dmode=4 -Ddumpreg=10 -f cbm -o viasr10.prg main.s
viasr10exp.prg: main.s
	acme -Dexpanded=1 -Dmode=4 -Ddumpreg=10 -f cbm -o viasr10exp.prg main.s
viasr14.prg: main.s
	acme -Dexpanded=0 -Dmode=5 -Ddumpreg=10 -f cbm -o viasr14.prg main.s
viasr14exp.prg: main.s
	acme -Dexpanded=1 -Dmode=5 -Ddumpreg=10 -f cbm -o viasr14exp.prg main.s
viasr18.prg: main.s
	acme -Dexpanded=0 -Dmode=6 -Ddumpreg=10 -f cbm -o viasr18.prg main.s
viasr18exp.prg: main.s
	acme -Dexpanded=1 -Dmode=6 -Ddumpreg=10 -f cbm -o viasr18exp.prg main.s
viasr1c.prg: main.s
	acme -Dexpanded=0 -Dmode=7 -Ddumpreg=10 -f cbm -o viasr1c.prg main.s
viasr1cexp.prg: main.s
	acme -Dexpanded=1 -Dmode=7 -Ddumpreg=10 -f cbm -o viasr1cexp.prg main.s

viasr00ifr.prg: main.s
	acme -Dexpanded=0 -Dmode=0 -Ddumpreg=13 -f cbm -o viasr00ifr.prg main.s
viasr00iex.prg: main.s
	acme -Dexpanded=1 -Dmode=0 -Ddumpreg=13 -f cbm -o viasr00iex.prg main.s
viasr04ifr.prg: main.s
	acme -Dexpanded=0 -Dmode=1 -Ddumpreg=13 -f cbm -o viasr04ifr.prg main.s
viasr04iex.prg: main.s
	acme -Dexpanded=1 -Dmode=1 -Ddumpreg=13 -f cbm -o viasr04iex.prg main.s
viasr08ifr.prg: main.s
	acme -Dexpanded=0 -Dmode=2 -Ddumpreg=13 -f cbm -o viasr08ifr.prg main.s
viasr08iex.prg: main.s
	acme -Dexpanded=1 -Dmode=2 -Ddumpreg=13 -f cbm -o viasr08iex.prg main.s
viasr0cifr.prg: main.s
	acme -Dexpanded=0 -Dmode=3 -Ddumpreg=13 -f cbm -o viasr0cifr.prg main.s
viasr0ciex.prg: main.s
	acme -Dexpanded=1 -Dmode=3 -Ddumpreg=13 -f cbm -o viasr0ciex.prg main.s
viasr10ifr.prg: main.s
	acme -Dexpanded=0 -Dmode=4 -Ddumpreg=13 -f cbm -o viasr10ifr.prg main.s
viasr10iex.prg: main.s
	acme -Dexpanded=1 -Dmode=4 -Ddumpreg=13 -f cbm -o viasr10iex.prg main.s
viasr14ifr.prg: main.s
	acme -Dexpanded=0 -Dmode=5 -Ddumpreg=13 -f cbm -o viasr14ifr.prg main.s
viasr14iex.prg: main.s
	acme -Dexpanded=1 -Dmode=5 -Ddumpreg=13 -f cbm -o viasr14iex.prg main.s
viasr18ifr.prg: main.s
	acme -Dexpanded=0 -Dmode=6 -Ddumpreg=13 -f cbm -o viasr18ifr.prg main.s
viasr18iex.prg: main.s
	acme -Dexpanded=1 -Dmode=6 -Ddumpreg=13 -f cbm -o viasr18iex.prg main.s
viasr1cifr.prg: main.s
	acme -Dexpanded=0 -Dmode=7 -Ddumpreg=13 -f cbm -o viasr1cifr.prg main.s
viasr1ciex.prg: main.s
	acme -Dexpanded=1 -Dmode=7 -Ddumpreg=13 -f cbm -o viasr1ciex.prg main.s


clean:
	rm -f $(TESTS)
	rm -f viasr.d64
