---
platform: emscripten 
generator: Ninja 
build_tool: ninja
build_type: Debug
cmake-toolchain: emscripten.toolchain.cmake
defines:
    FIPS_NO_ASSERTS_IN_RELEASE: ON
    FIPS_EMSCRIPTEN_USE_WASM: ON
    FIPS_EMSCRIPTEN_USE_CWRAP: ON
    FIPS_EMSCRIPTEN_MEM_INIT_METHOD: 0
#    FIPS_EMSCRIPTEN_USE_CLOSURE: ON
    FIPS_EMSCRIPTEN_USE_EMMALLOC: ON
    FIPS_EMSCRIPTEN_RELATIVE_SHELL_HTML: "examples/common/shell.html"
    FIPS_EMSCRIPTEN_TOTAL_MEMORY: 33554432


